### ISSUE TITLE
Esse projeto ainda está disponível para download?

### ISSUE THREAD

**Issue by caiovfelipe** [lendadadti/g-horarios#1]
Estou querendo testar esse programa, mas, pelo tempo que ele já foi criado, gostaria de saber se ele ainda está disponível no gitlab

**Comment by lendadadti** [comment]
Está sim, amigo =D

Você pode fazer o clone do próprio GitHub, inclusive.

**Comment by caiovfelipe** [comment]
Que bom! Valeu pelo retorno

**Comment by lendadadti** [comment]
Qualquer dúvida que vier a ter, não hesite em perguntar.

Obrigado pelo interesse em software livre =D
